spring:
  application:
    name: shuttleverse-community

  datasource:
    url: jdbc:postgresql://127.0.0.1:54322/postgres?user=postgres&password=postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  
  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: "http://shuttleverse-service-discovery:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET_KEY:-${TEST_JWT_SECRET_KEY}}

server:
  servlet:
    context-path: /api/community/v1
  port: 8083
