logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

spring:
  application:
    name: shuttleverse-community

  datasource:
    url: jdbc:postgresql://127.0.0.1:54322/postgres?user=postgres&password=postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 10000
      max-lifetime: 300000
      connection-timeout: 30000

  devtools:
    restart:
      enabled: true

    livereload:
      enabled: false

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 165MB
      max-request-size: 165MB

eureka:
  client:
    service-url:
      defaultZone: "http://shuttleverse-service-discovery:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET_KEY:-${TEST_JWT_SECRET_KEY}}

cloudflare:
  r2:
    account-id: ${R2_ACCOUNT_ID:test}
    access-key: ${R2_ACCESS_KEY:test}
    secret-key: ${R2_SECRET_KEY:test}
    bucket: ${R2_BUCKET:test}
    public-base-url: ${R2_PUBLIC_BASE_URL:https://test.com}

server:
  servlet:
    context-path: /api/community/v1
  port: 8083
