spring:
  application:
    name: shuttleverse-community

  datasource:
    url: jdbc:postgresql://127.0.0.1:54322/postgres?user=postgres&password=postgres

  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  profiles:
    default: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${GOOGLE_ISSUER_URI:https://accounts.google.com}
          jwk-set-uri: ${GOOGLE_JWK_SET_URI:https://www.googleapis.com/oauth2/v3/certs}

eureka:
  client:
    service-url:
      defaultZone: "http://shuttleverse-service-discovery:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true
  max-age: 3600
