apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttleverse-community
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttleverse-community
  template:
    metadata:
      labels:
        app: shuttleverse-community
    spec:
      containers:
        - name: shuttleverse-community
          image: docker-user/shuttleverse-community:latest
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: POSTGRESQL_PROD_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRESQL_PROD_URI
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: r2-account-id
                  key: R2_ACCOUNT_ID
            - name: R2_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-access-key
                  key: R2_ACCESS_KEY
            - name: R2_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret-key
                  key: R2_SECRET_KEY
            - name: R2_BUCKET
              valueFrom:
                secretKeyRef:
                  name: r2-bucket
                  key: R2_BUCKET
            - name: R2_PUBLIC_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: r2-public-base-url
                  key: R2_PUBLIC_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: shuttleverse-community
  namespace: default
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: shuttleverse-community
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP