apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttleverse-community
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttleverse-community
  template:
    metadata:
      labels:
        app: shuttleverse-community
    spec:
      containers:
        - name: shuttleverse-community
          image: docker-user/shuttleverse-community:latest
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: POSTGRESQL_PROD_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRESQL_PROD_URI
---
apiVersion: v1
kind: Service
metadata:
  name: shuttleverse-community
  namespace: default
spec:
  selector:
    app: shuttleverse-community
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP